services:
  bot:
    build:
      context: .
    pull_policy: build
    env_file:
      - stack.env
    ports:
      - 3002:3000
    volumes:
      - /var/www/docker/kurovskyi-secret-bot/data:/usr/src/data
      # - ./data:/usr/src/data
